In [1]:
def leapyear(a):
     if a %4==0 :
            print("leap ")

In [2]:
leapyear(1700
    )

leap 


In [10]:
import numpy as np 


In [11]:
# creationg an array 

arr = np.array([1,2,3,4,5])

In [15]:
# datatype of an array 
arr =np.array([1,2,3,4,5],dtype=str)

In [16]:
arr=np.arange(10,40,2)

In [17]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [18]:
np.insert (arr,5,int(40))

array([10, 12, 14, 16, 18, 40, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [19]:
np.delete(arr,5)

array([10, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [21]:
arr =np.insert(arr,0,100)
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [22]:
np.append(arr,50)

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38,  50])

In [23]:
arr = arr.astype(int)

In [24]:
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [ ]:
# matrices

In [48]:
mat =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12,]])
print( mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
# speed list 
a =[i for i in range (10000000)]
b=[i for i in range (10000000,20000000)]
c= []
import time 
start = time.time()
for i in range (len(a)):
        c.append(a[i]+b[i])
print(time.time()-start)

1.2430109977722168


In [45]:
arr1=np.arange(10000000)
arr2=np.arange(10000000,20000000)
import time 
start = time.time()
arr3=arr1+arr2
print(time.time()-start)

0.011995315551757812


In [44]:
6.4/0.46



13.91304347826087

In [41]:
printt(time.time)

<built-in function time>


In [49]:
print(mat)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
mat[1,2]

7

In [58]:
for i in range (3):
    print(mat[i,1])

2
6
10


In [61]:
d3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12,[13,31,35,35]]]])

C:\Users\utkal\AppData\Local\Temp\ipykernel_19944\118544508.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12,[13,31,35,35]]]])


In [62]:
d3[1]

[[9, 10, 11, 12, [13, 31, 35, 35]]]

In [ ]:
dn=np.array([3],ndarray=5)